<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
شکلات‌های خوب‌تر
</font>
</h1>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
فرض کنید که بعد از میل کردن چند شکلات معمولی (غیر دارک) متوجه شده‌ایم که بسیاری از آن‌ها هم خوشمزه هستند و اگر بتوانیم موارد با کیفیت‌تر آن‌ها را پیدا کنیم احتمالاً فروش خوبی خواهند داشت. پس در گام آخر از پروژه می‌خواهیم شرکت‌هایی که شکلات‌های باکیفیت‌تری را تولید می‌کنند شناسایی کرده و شکلات‌های ‌‌آن‌ها را جدا کنیم.
</font>
</p>


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در گام پیشین قیمت شکلات‌ها را تخمین زده و دیتافریم نهایی را در فایلی به نام <code>chocolate_price.csv</code> ذخیره کردید. در ابتدا آن فایل را به شکل یک دیتافریم بخوانید.
</font>
</p>


In [142]:
import numpy as np
import pandas as pd

df = pd.read_csv('chocolate_price.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'chocolate_price.csv'

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت اول
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
توجه داشته باشید که در این گام تنها با شکلات‌های غیرتلخ کار داریم. پس در ابتدا تنها شکلات‌هایی که درصد کاکائوی آن‌ها کمتر یا مساوی  ۷۰ درصد است را جدا کرده و در دیتافریم <code>df</code> ذخیره کنید.
</font>
</p>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
بعد از جداسازی و ساخت دیتافریم، به کمک تابع <code dir=ltr>reset_index()</code> نمایه‌ها را ریست کنید. در این مرحله به آرگومان‌های <code>inplace</code> و <code>drop</code> هم توجه کنید.
</font>
</p>

In [77]:
df = df.loc[df['Cocoa Percent'] < 70]
df.reset_index(inplace=True , drop=True)
df


Company       Specific Bean Origin  Review Date  \
0              A. Morin                Agua Grande         2016   
1              A. Morin       Chanchamayo Province         2013   
2              A. Morin                       Peru         2012   
3                   Adi                 Vanua Levu         2011   
4    Aequare (Gianduja)  Los Rios, Quevedo, Arriba         2009   
..                  ...                        ...          ...   
323              Zotter              Indianer, Raw         2012   
324              Zotter                      Congo         2011   
325              Zotter               Kerala State         2011   
326              Zotter               Kerala State         2011   
327              Zotter         Brazil, Mitzi Blue         2010   

     Cocoa Percent Company Location  Rating           Bean Type  \
0             63.0           France    75.0               Blend   
1             63.0           France    80.0               Blend   
2             63.0           France    75.0               Blend   
3             60.0             Fiji    55.0          Trinitario   
4             55.0          Ecuador    55.0  Forastero (Arriba)   
..             ...              ...     ...                 ...   
323           58.0          Austria    70.0               Blend   
324           65.0          Austria    60.0           Forastero   
325           65.0          Austria    70.0           Forastero   
326           62.0          Austria    65.0               Blend   
327           65.0          Austria    60.0               Blend   

    Broad Bean Origin  price(100g)  
0            Sao Tome     118125.0  
1                Peru     126000.0  
2                Peru     118125.0  
3                Fiji      82500.0  
4             Ecuador      75625.0  
..                ...          ...  
323             Other     101500.0  
324             Congo      97500.0  
325             India     113750.0  
326             India     100750.0  
327            Brazil      97500.0  

[328 rows x 9 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت دوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این قسمت به ازای هر شرکت شکلات‌سازی، میانگین امتیاز شکلات‌های آن را برای هر سال محاسبه کرده و همچون جدول زیر در دیتافریم <code>companies</code> ذخیره کنید.

<center>

| | 2006 | ... | 2015 | 2016 | 2017 |
| :---: | :---: | :---: | :---: | :---: | :---: |
| A. Morin | NaN | ... | 63.75 | 75.0 | NaN |
| ... | ... | ... | ... | ... | ...  |
| hexx | NaN | ... | 60.00 | NaN | NaN |
| twenty-four blackbirds | NaN | ... | NaN | NaN | NaN |

</center>
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
بعد از استفاده از دستور <code>groupby</code> و محاسبه‌ی میانگین از دستور <code>unstack</code> استفاده کنید.
</font>
</p>

In [78]:
companies = df.groupby(by=['Company','Review Date'])['Rating'].mean().unstack()
companies

Review Date             2006  2007  2008  2009  2010  2011  2012  2013  2014  \
Company                                                                        
A. Morin                 NaN   NaN   NaN   NaN   NaN   NaN  75.0  80.0   NaN   
AMMA                     NaN   NaN   NaN   NaN  77.5   NaN   NaN   NaN   NaN   
Adi                      NaN   NaN   NaN   NaN   NaN  55.0   NaN   NaN   NaN   
Aequare (Gianduja)       NaN   NaN   NaN  55.0   NaN   NaN   NaN   NaN   NaN   
Alain Ducasse            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  55.0   
...                      ...   ...   ...   ...   ...   ...   ...   ...   ...   
Zak's                    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
Zokoko                   NaN   NaN   NaN   NaN   NaN  70.0   NaN   NaN   NaN   
Zotter                   NaN   NaN   NaN   NaN  60.0  65.0  70.0   NaN   NaN   
hello cocoa              NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
twenty-four blackbirds   NaN   NaN   NaN   NaN   NaN   NaN   NaN  65.0   NaN   

Review Date             2015  2016  
Company                             
A. Morin                 NaN  75.0  
AMMA                     NaN   NaN  
Adi                      NaN   NaN  
Aequare (Gianduja)       NaN   NaN  
Alain Ducasse            NaN   NaN  
...                      ...   ...  
Zak's                   60.0   NaN  
Zokoko                   NaN  65.0  
Zotter                   NaN   NaN  
hello cocoa             55.0   NaN  
twenty-four blackbirds   NaN   NaN  

[159 rows x 11 columns]

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
خطوط زیر برای استانداردسازی شکل جدول اعمال می‌شوند. این خطوط را تغییر نداده و تنها سلول زیر را اجرا کنید.
</font>
</p>

In [79]:
companies.columns.name = None
companies.index.name = None
companies

2006  2007  2008  2009  2010  2011  2012  2013  2014  \
A. Morin                 NaN   NaN   NaN   NaN   NaN   NaN  75.0  80.0   NaN   
AMMA                     NaN   NaN   NaN   NaN  77.5   NaN   NaN   NaN   NaN   
Adi                      NaN   NaN   NaN   NaN   NaN  55.0   NaN   NaN   NaN   
Aequare (Gianduja)       NaN   NaN   NaN  55.0   NaN   NaN   NaN   NaN   NaN   
Alain Ducasse            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  55.0   
...                      ...   ...   ...   ...   ...   ...   ...   ...   ...   
Zak's                    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
Zokoko                   NaN   NaN   NaN   NaN   NaN  70.0   NaN   NaN   NaN   
Zotter                   NaN   NaN   NaN   NaN  60.0  65.0  70.0   NaN   NaN   
hello cocoa              NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
twenty-four blackbirds   NaN   NaN   NaN   NaN   NaN   NaN   NaN  65.0   NaN   

                        2015  2016  
A. Morin                 NaN  75.0  
AMMA                     NaN   NaN  
Adi                      NaN   NaN  
Aequare (Gianduja)       NaN   NaN  
Alain Ducasse            NaN   NaN  
...                      ...   ...  
Zak's                   60.0   NaN  
Zokoko                   NaN  65.0  
Zotter                   NaN   NaN  
hello cocoa             55.0   NaN  
twenty-four blackbirds   NaN   NaN  

[159 rows x 11 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت سوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
برای پیدا کردن بهترین شرکت‌ها می‌خواهیم تنها امتیاز سال‌های ۲۰۱۲ به بعد را در نظر بگیریم (خود سال ۲۰۱۲ را هم در نظر بگیرید).
ابتدا به ازای هر کمپانی، میانگین امتیاز سال‌های ۲۰۱۲ به بعد آن را محاسبه کرده و در متغیر <code>mean_ratings</code> ذخیره کنید.
توجه داشته باشید که خروجی شما باید یک سری پانداز (<code>pd.Series</code>) باشد.
</font>
</p>


In [91]:
#just_2012_after = df.loc[df['Review Date'] >= 2012]
#mean_ratings = just_2012_after.groupby(by=['Company'])['Rating'].mean()
#mean_ratings
mean_ratings = companies.iloc[ : , 6:].mean(axis=1)
mean_ratings

A. Morin                  76.666667
AMMA                            NaN
Adi                             NaN
Aequare (Gianduja)              NaN
Alain Ducasse             55.000000
                            ...    
Zak's                     60.000000
Zokoko                    65.000000
Zotter                    70.000000
hello cocoa               55.000000
twenty-four blackbirds    65.000000
Length: 159, dtype: float64

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
اکنون به کمک میانگین امتیاز هر کمپانی (<code>mean_ratings</code>)، ۱۰ کمپانی با بهترین امتیاز را پیدا کنید و در متغیر <code>best_ratings</code> ذخیره کنید. توجه داشته باشید که خروجی شما باید یک سری پانداز (<code>pd.Series</code>) باشد.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<span style="color:purple"><b>توجه:</b></span>
در مواردی که امتیاز کمپانی‌ها یکسان باشد، باید کمپانی را براساس ترتیب حروف الفبا انتخاب کنید. به‌عنوان مثال اگر دو کمپانی <code>A</code> و <code>B</code> هر دو میانگین امتیاز <code>75.00</code> داشته باشند، اولویت با شرکت <code>A</code> است.
</font>
</p>

In [137]:
mean_ratings_copy = mean_ratings.copy().reset_index()
best_ratings = mean_ratings_copy.sort_values(by=[0, "index"],ascending=[False,True]).set_index('index').squeeze().head(10)
best_ratings

index
Matale                                  80.000000
Patric                                  80.000000
A. Morin                                76.666667
Valrhona                                76.666667
Askinosie                               75.000000
Bonnat                                  75.000000
Brasstown aka It's Chocolate            75.000000
Fossa                                   75.000000
Heirloom Cacao Preservation (Zokoko)    75.000000
L.A. Burdick (Felchlin)                 75.000000
Name: 0, dtype: float64

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت چهارم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
اکنون شکلات‌هایی که کمپانی سازنده‌شان جزو ۱۰ شرکت برتر (<code>best_ratings</code>) است را از دیتافریم <code>df</code> انتخاب کرده و در دیتافریم <code>chocolates_to_sell</code> ذخیره کنید.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<span style="color:green"><b>راهنمایی ۱:</b></span>
بعد از انتخاب این شکلات‌ها، به‌کمک دستور <code>reset_index</code> نمایه‌ها را ریست کنید. استفاده از آرگومان <code>drop</code> را نیز فراموش نکنید.

<br>
<span style="color:green"><b>راهنمایی ۲:</b></span>
برای بررسی وجود یک متغیر در یک لیست می‌توانید از تابع <code>isin</code> استفاده کنید.
</font>
</p>

In [135]:
chocolates_to_sell = df.loc[df['Company'].isin(best_ratings.index)].reset_index(drop=True)
chocolates_to_sell

Company  \
0                               A. Morin   
1                               A. Morin   
2                               A. Morin   
3                              Askinosie   
4                                 Bonnat   
5           Brasstown aka It's Chocolate   
6                                  Fossa   
7   Heirloom Cacao Preservation (Zokoko)   
8                L.A. Burdick (Felchlin)   
9                L.A. Burdick (Felchlin)   
10               L.A. Burdick (Felchlin)   
11                                Matale   
12                                Patric   
13                                Patric   
14                              Valrhona   
15                              Valrhona   
16                              Valrhona   
17                              Valrhona   
18                              Valrhona   
19                              Valrhona   
20                              Valrhona   
21                              Valrhona   
22                              Valrhona   
23                              Valrhona   
24                              Valrhona   
25                              Valrhona   
26                              Valrhona   
27                              Valrhona   
28                              Valrhona   

                     Specific Bean Origin  Review Date  Cocoa Percent  \
0                             Agua Grande         2016           63.0   
1                    Chanchamayo Province         2013           63.0   
2                                    Peru         2012           63.0   
3                                  Mababa         2016           68.0   
4                                  Surfin         2014           65.0   
5                                Conacado         2015           68.0   
6            Kokoa Kamili Coop, Kilombero         2016           67.0   
7         Alto Beni, Upper Rio Beni, 2015         2016           68.0   
8                                   Chuao         2012           68.0   
9                              Madagascar         2009           64.0   
10                               Bolivian         2009           68.0   
11                            Somia, 2013         2013           68.0   
12                             Madagascar         2009           67.0   
13          Piura, Choc. Garage Exclusive         2013           67.0   
14               Piura, Illanka, Quemazon         2015           63.0   
15                   Loma Sotavento, 2013         2013           64.0   
16                      Otucan, Grand Cru         2012           69.0   
17                                Caraque         2011           56.0   
18                    Porcelana, Pedegral         2011           64.0   
19                                Tainori         2009           64.0   
20                                 Alpaco         2009           66.0   
21                                Nyangbo         2009           68.0   
22                          Chuao 2002 P.         2007           65.0   
23                                Manjari         2007           64.0   
24  Porcelana, Maracaibo, Palmira P. 2006         2007           64.0   
25                                Caraibe         2006           66.0   
26                     Gran Couva 2005 P.         2006           64.0   
27  Porcelana, Maracaibo, Palmira P. 2005         2006           64.0   
28   Sambirano, Ampamakia 2005, Millot P.         2006           64.0   

   Company Location  Rating            Bean Type  \
0            France    75.0                Blend   
1            France    80.0                Blend   
2            France    75.0                Blend   
3            U.S.A.    75.0           Trinitario   
4            France    75.0                Blend   
5            U.S.A.    75.0                Blend   
6         Singapore    75.0           Trinitario   
7            U.S.A.    75.0          Amazon, ICS   
8            U.S.A.    75.0           Trinitario   
9

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت پنجم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در نهایت مجموع قیمت این شکلات‌ها (<code>chocolates_to_sell</code>) را در متغیر <code>priceSum</code> ذخیره کنید تا مجموع دریافتی ما از این شکلات‌ها هم مشخص شود.
</font>
</p>

In [140]:
priceSum = chocolates_to_sell['price(100g)'].sum()
priceSum

np.float64(3419625.0)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [141]:
import zlib
import zipfile

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

df.to_csv('normal_chocolates.csv', index = True)
companies.to_csv('companies.csv', index = True)
chocolates_to_sell.to_csv('chocolates_to_sell.csv', index = True)
mean_ratings.to_csv("mean_ratings.csv", index = True)
best_ratings.to_csv("best_ratings.csv", index = True)

np.savez("answers.npz" ,priceSum = priceSum)
file_names = ["answers.npz", "project1_step3.ipynb", "chocolates_to_sell.csv", 
              "companies.csv", "mean_ratings.csv", "best_ratings.csv", "normal_chocolates.csv"]
compress(file_names)

File Paths:
['answers.npz', 'project1_step3.ipynb', 'chocolates_to_sell.csv', 'companies.csv', 'mean_ratings.csv', 'best_ratings.csv', 'normal_chocolates.csv']
